config/routes.rb
Rails.application.routes.draw do
  get   'inquiry'         => 'inquiry#contact'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def contact
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'contact'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'contact'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))    
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>お問い合わせ - YOGAI</title>

<meta name="viewport" content="width=device-width">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Exo+2:400,700" rel="stylesheet">

<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<header>
		<div class="container">
		
		<a href="index.html">YOGAI</a>
		
      <nav>
        <ul>
          <li><a href="index.html">トップ</a></li>
          <li><a href="about.html">サイトについて</a></li>
          <li><a href="inquiry#contact">お問い合わせ</a></li>
        </ul>
      </nav>
	
		</div>
		</header>
		
		<div class="contents">
        <div class="container">
          <article>
            <h1>お問い合わせ 確認</h1>
              <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>

                   <p>
                    <label>
                      名前<span class="text-danger">（必須）</span>
                      <%= f.hidden_field :name %>
                      <%= @inquiry.name %>
				          	</label>
                  </p>                    
                   <p>
                    <label>
                      メールアドレス<span class="text-danger">（必須）</span>
                      <%= f.hidden_field :email %>
                      <%= @inquiry.email %>
                   	</label>
                  </p> 

                   <p>
                    <label>
                       お問い合わせ：
                      <%= f.hidden_field :message %>
                      <%= simple_format(@inquiry.message) %>
                    	</label>
                  </p>   

                <%= f.submit '送信', :class => 'btn btn-primary' %>
              <% end %>
          </article>	

        <div class="sub">
        <aside class="profile">
        <h2>PROFILE</h2>
        <figure>
        <%= image_tag 'foot.svg' %>
        </figure>
        <p>街歩き＆食べ歩きがライフスタイル。天気がいい日はあちこちに出没しています。</p>
		</aside>
		
		
		<aside class="topics">
		<h2>TOPICS</h2>
		
		<ul>
		<li>
		<a href="#">
			<figure><%= image_tag 'fruits.jpg' %></figure>
			<h3>甘いトマトとすっぱいトマト</h3>
		</a>
		</li>
		
		<li>
		<a href="#">
			<figure><%= image_tag 'cycle.jpg' %></figure>
			<h3>自転車で行けるところまで行ってみる</h3>
		</a>
		</li>
		
		<li>
		<a href="#">
			<figure><%= image_tag 'green.jpg' %></figure>
			<h3>緑のワンポイント</h3>
		</a>
		</li>
		
		<li>
		<a href="#">
			<figure><%= image_tag 'time.jpg' %></figure>
			<h3>タイムアタックでやる気を出してみる</h3>
		</a>
		</li>
		</ul>
		</aside>
		</div>
		
		</div>
		</div>
		
		
		<footer>
		© YOGAI
		</footer>
		
		
		</body>
		</html>

app/views/inquiry/contact.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>お問い合わせ - YOGAI</title>

<meta name="viewport" content="width=device-width">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Exo+2:400,700" rel="stylesheet">

<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<header>
		<div class="container">
		
		<a href="index.html">YOGAI</a>
		
		<nav>
			<ul>
					<li><a href="index.html">トップ</a></li>
					<li><a href="about.html">サイトについて</a></li>
					<li><a href="inquiry#contact">お問い合わせ</a></li>
			</ul>
		</nav>
		
		</div>
		</header>
		<div class="contents">
			<div class="container">
			<article>
				<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
					<% if @inquiry.errors.any? %>
						<div class="alert alert-danger" role="alert">
							<strong>入力内容にエラーがあります</strong>
							<ul>
								<% @inquiry.errors.each do |attr, msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>

				<h1>お問い合わせ</h1>
				<p>ご意見、ご感想などがありましたら、以下の欄にご記入の上、送信してください。記事に関するご質問などもお気軽にお寄せください。</p>
			 	 <p>
          <label>
						名前<span class="text-danger">（必須）</span>
						<%= f.text_field :name %>
        </label>
       </p>

        <p>
          <label>
						メールアドレス<span class="text-danger">（必須）</span>
						<%= f.text_field :email %>
					</label>
        </p>

         <p>
          <label>
						お問い合わせ：
						<%= f.text_area :message %>	
			  	</label>
				</p>

					<%= f.submit '確認', class: 'btn btn-primary' %>
					<% end %>
	  	</article>
		
		
		<div class="sub">
			<aside class="profile">
				<h2>PROFILE</h2>
						<figure>
						<%= image_tag 'foot.svg' %>
						<%# <img src="img/foot.svg" alt="YOGAIの管理人"> %>
						</figure>
				<p>街歩き＆食べ歩きがライフスタイル。天気がいい日はあちこちに出没しています。</p>
			</aside>
			
		
				<aside class="topics">
				<h2>TOPICS</h2>
						<ul>
							<li>
									<a href="#">
										<figure><%= image_tag 'fruits.jpg' %></figure>
										<h3>甘いトマトとすっぱいトマト</h3>
									</a>
							</li>
						
							<li>
									<a href="#">
										<figure><%= image_tag 'cycle.jpg' %></figure>
										<h3>自転車で行けるところまで行ってみる</h3>
									</a>
							</li>
				
							<li>
									<a href="#">
										<figure><%= image_tag 'green.jpg' %></figure>
										<h3>緑のワンポイント</h3>
									</a>
							</li>
				
							<li>
									<a href="#">
											<figure><%= image_tag 'time.jpg' %></figure>
											<h3>タイムアタックでやる気を出してみる</h3>
									</a>
							</li>
						</ul>
				</aside>
		  	</div>	
	  	</div>
		</div>
		
		
				<footer>
				© YOGAI
				</footer>
  		</body>
		</html>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Townwalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>